### ISSUE TITLE
Hello, i would order scripts for onmyoji global, i can buy it.

### ISSUE THREAD

**Issue by pyx232** [society765/yys-auto-yuhun#1]
Hello, i would order scripts/bot for onmyoji global, i can buy it, please help or contact me through my mail: pyx.232@gmail.com.
Thanks for reading my mess.

**Comment by xwang233** [comment]
Thank you for being interested in my project. However, I do not offer commercial support. Please feel free to fork and write your own code, or post any issues while using the product. Thank you.
