### ISSUE TITLE
如何实现遮挡也能进行识别和鼠标点击的？

### ISSUE THREAD

**Issue by yk133** [society765/yys-auto-yuhun#12]
如何实现遮挡也能进行识别和鼠标点击的？想学习一下相关知识

**Comment by xwang233** [comment]
你好！后台找图找色要用到 windows 的 API，你可以自己去查。我使用了封装好的 天使插件，他们的底层代码是用 C++ 写的，你可以在他们论坛找到对应的 documentation。

这位 https://github.com/AcademicDog/onmyoji_bot 使用了 win32 API，你也可以参考一下。

**Comment by yk133** [comment]
非常感谢！
