### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by tiketiskte** [society765/yys-auto-yuhun#13]
After the interface is updated, the script frequently selects between locking the lineup and unlocking the lineup. It will not detect the challenge picture and enter the challenge interface.

**Comment by xwang233** [comment]
感谢反馈。已更新双开脚本 dual.py 中对应的坐标和颜色。欢迎反馈其他问题。 

Thanks for the feedback. I have already updated the coordinates and colors in `dual.py`. Further follow-ups are welcome.
