### ISSUE TITLE
在点击怪物的设计上能否有进一步优化空间？

### ISSUE THREAD

**Issue by denleey** [society765/yys-auto-yuhun#14]
网易推出了智能技能释放模式，那么以前点怪，现在可以点队友。
点怪的部分是每进一次场景都会一直点击（或者随机某个时间点击一次）
可否增加一个函数，点击队友，开场点击一次，直到判定结束前都不点队友了（脑残机制设置为点队友，下个场景可以继承，点击两次则会取消标记）

**Comment by xwang233** [comment]
感谢你的反馈。

> 可否增加一个函数，点击队友，开场点击一次，直到判定结束前都不点队友了（脑残机制设置为点队友，下个场景可以继承，点击两次则会取消标记）

这个脚本的应用场景主要是刷魂十，御灵，觉醒材料。在这些环境下，点某个友方式神的提升并不是很显著，比如现在大部分魂十队伍甚至可以做到不点怪全自动，点击友方式神只有很少提升；又比如桃花会自动主目标给血最少的加血。而且在这三个副本中，式神站位还不同，需要分别添加坐标。综上，我不打算添加点击友方式神的功能。

你可以 fork, clone 这个 repo 到你的电脑上，然后自行添加类似功能。只需在进入战斗后的语句附近，添加点击对应坐标的函数 `crnd` 即可。

欢迎反馈其他 bug 或意见。

**Comment by denleey** [comment]
感谢作者的回复，没想到还能活捉一只大佬，这也是最近出了新式神后的一个想法 烬天玉藻前刷魂十一的时候，利用妖琴拉一次可以做到魂十一19秒 而烬天玉藻前因为被动的奇葩，吸队友攻击只能在一号位，也就是最左侧的位置才能生效。所以才有这个想法的。

发自我的iPhone

**Comment by xwang233** [comment]
这个我确实不知道，因为已经弃坑很久了，我只做一些基本功能的维护。如果确实需要类似功能的话，添加一两行语句也不难。感谢反馈。

**Comment by denleey** [comment]
您好，因为我不太懂python,而且好像这个python也是根据autohotkey改过来的 函数的用法不清楚，我尝试直接在点击怪物的那里改坐标，发现双人的脚本就行不通，原本函数设计的点怪应该是短暂的连点 一直会执行，但是网易奇葩的设置，点击队友如果连点两次则会取消标记，于是我又常识在点击之后break，还是存在问题 break后就不能判定双人组队是否结束了 不会重新邀请开启下一轮。最后想到通过这种方式联系作者，看是否能根据这个改进。感谢回复。

发自我的iPhone
