### ISSUE TITLE
检测识图那一块的代码

### ISSUE THREAD

**Issue by denleey** [society765/yys-auto-yuhun#15]
检测识图，颜色测试那里，能否解释一下 
   while True:
        tscoldebug = ts.GetColor(1, 1)
        print(tscoldebug)
        if tscoldebug != "000000" and tscoldebug != "FFffff":
            break
        mysleep(200)
    print('passed color debug')
现在界面换颜色之后，挑战的坐标以及单刷进去的界面变化挺大，想修改这个代码，但是不懂这段的具体意思。

**Comment by xwang233** [comment]
@denleey 你好，这部分的代码是 debug 用的，如果窗口绑定失败，经常会出现颜色获取就是一片黑 #000000 或者一片白 #FFFFFF，所以这里添加代码测试窗口颜色获取是否正常。

如果游戏的 UI 改变了，那么对应部分判断战斗开始/结束的颜色及坐标就可能需要修改。你可以参考 wtfc1() 各个 arguments 的具体定义，修改对应的坐标和颜色来达到你想要的功能。由于代码使用了后台模式和窗口绑定，所有坐标都是窗口的相对坐标。
