### ISSUE TITLE
关于颜色测试那一块儿代码问题

### ISSUE THREAD

**Issue by denleey** [society765/yys-auto-yuhun#16]
您好，在您的代码基础上修改了几次，一直想请教一下，颜色测试那块儿代码的作用，现在游戏的界面变化了 单开的时候一直提醒colordebug那块儿不正确。望指导，谢谢 期待您的回复。

**Comment by xwang233** [comment]
你好，如果colordebug错了的话，最可能的原因是你没有用管理员权限运行游戏和脚本。这个应该跟游戏界面改动无关。

**Comment by denleey** [comment]
了解，感谢回复。谢谢！！！
