### ISSUE TITLE
能否留下一个联系方式，我重新跑了一边单人御魂，colordebug还是出问题。

### ISSUE THREAD

**Issue by denleey** [society765/yys-auto-yuhun#17]
单人御魂在colordebug函数过后直接输出一个颜色代码，不继续往下跑。项目已经开启了管理员权限还是不行。能否留下一个联系方式指导一下或者小小更新一下单人模式？感谢

**Comment by denleey** [comment]
具体代码如下
while True:
        tscoldebug = ts.GetColor(1, 1)
        print(tscoldebug)
        if tscoldebug != "000000" and tscoldebug != "ffffff":
            break
        mysleep(200)
    print('passed color debug')

**Comment by denleey** [comment]
822719064

**Comment by xwang233** [comment]
单人挑战的游戏内 UI 更新了。我也更新了“挑战”按钮对应的坐标和颜色。感谢使用，欢迎其他反馈。

**Comment by denleey** [comment]
单人御灵跟单人业原火依然是输出ffffff  不能进入点击挑战的那一步 感谢作者解决
