### ISSUE TITLE
为什么点击F10进入对战界面后无法自动点击“准备”？

### ISSUE THREAD

**Issue by BlackBaiX** [society765/yys-auto-yuhun#2]

**Comment by xwang233** [comment]
你使用的是win7系统么 win7需要调整画面设置
右键我的电脑 -> 高级系统设置 -> 高级 -> 设置 -> 取消勾选以下3项： "启用 Aero peek"，"启用透明玻璃"，和"启用桌面组合"。

**Comment by BlackBaiX** [comment]
本来win7也设置了。。但是不行，所以换成win10系统后就解决了。谢谢大佬！

**Comment by xwang233** [comment]
多谢你的反馈 我回去检查一下不兼容的原因
