### ISSUE TITLE
2019/3/28失效

### ISSUE THREAD

**Issue by XERO75** [society765/yys-auto-yuhun#3]
更新最新版本后失效了

**Comment by xwang233** [comment]
你好！我在去年已经退坑yys了，手边没有游戏或者账号可以debug。不知道你所说的`更新最新版本后失效了`具体表现为什么呢？如果是游戏内的UI或者按钮位置变更了的话，你需要手动修改下代码中对应按钮的坐标，或者颜色。

**Comment by kraviszhong** [comment]
运行脚本后能自动点击开始按钮，但进入战斗界面无法自动点击怪物，坐标没变，我觉得可能是进入战斗界面后不能运行鼠标点击，不是专业的所以只是大概猜想

**Comment by xwang233** [comment]
@kraviszhong 你好，感谢你的反馈！如果可以自动点击开始按钮，但是在战斗中不能点怪的话，我猜测是这两种原因之一 

1. 我的代码中，点击“准备”后，判断是否进入战斗是根据 UI 左下角“自动”齿轮上某一个点是否变为对应的白色来判断的。因为“自动”这两个字不会随战斗画面摆动，同样的颜色也适用于“御魂”，“觉醒”，“御灵”等其他副本，所以效果很好。不知道这次更新是否修改了左下角这部分的UI呢？如果脚本无法找到对应的颜色，那么无法进入点怪的部分。

2. 当确实进入战斗后，脚本会根据之前的选择，点击中间或者右边怪物，实现方法就是在对应的矩形屏幕区域随机点击。如果怪物位置移动了的话，可能会点不到或者点错。验证脚本是否在屏幕里随机点击的方法很简单，你可以尝试缓慢拖拽视角或者移动游戏窗口，如果发现视角有奇怪的突然变化，说明脚本在点怪，可能只是没点到而已。

如果愿意的话，你们可以下载 [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) 去简单看一下 debug 信息。我在每一步后边都加了 OutputDebug 输出，可以使用这个程序来判断脚本执行到哪一步后出错。

**Comment by kraviszhong** [comment]
到了Already click TIAO-ZHAN，没有到ZHUN-BEI，所以是没有push到开始战斗和点怪，我看了下准备的坐标好像不对，我截图了（图上鼠标放在了准备的地方），还有一个一直不会的问题，我用Autohotkey运行 onmyoji_yys-auto-yuhun.ahk，都是没有注册成功，运行不了
![2](https://user-images.githubusercontent.com/49083390/55400725-3c296a00-5581-11e9-9fcc-7068419e0000.png)
。

**Comment by xwang233** [comment]
@kraviszhong 感谢你的反馈！如果没有运行到ZHUN-BEI, 可能是“准备”附近某个地方颜色错了。我大概需要几天时间来建一个新号 debug。 

你需要同时下载两个 ahk 文件和 TSPlug.dll 才能注册插件，不知道这是不是你注册失败的问题所在呢。

**Comment by kraviszhong** [comment]
可以确认是准备图案跟以前版本较上移了一些位置（之前鼓和小灯笼一样挨着窗口下端），我是直接下载整个源压缩包的，插件是可以注册成功的，但出现了Error返回的是register fail ，这个我搞不懂，希望能够得到解答，谢谢！
![5](https://user-images.githubusercontent.com/49083390/55421939-14e89200-55ad-11e9-917f-fc6e0351421d.jpg)

**Comment by xwang233** [comment]
@kraviszhong 你是说使用发布的 exe 文件可以正常运行，但是用 AHK 运行 onmyoji_yys-auto-yuhun.ahk 源码就会注册失败？我去年是使用 win7 发布的 exe 文件，不知道对 win10 的兼容性怎么样。

我大概需要几天时间来调试一下。感谢反馈！

**Comment by xwang233** [comment]
@XERO75 @kraviszhong 我已经更新了AHK源码和release。更新中注释掉了点击“准备”的部分，现在需要勾选“阵容锁定”，让YYS系统自动准备，也可以避免以后“准备”UI再修改的问题。

感谢测试并提供反馈！

**Comment by AcademicDog** [comment]
我等了几个月，终于更新了，想哭

**Comment by Milo-dd** [comment]
不知道当我输入了0，之后发现并不能自动开启战斗，是什么问题呢
![image](https://user-images.githubusercontent.com/37180767/56979365-3b99e880-6bac-11e9-981b-4b22f5765143.png)
