### ISSUE TITLE
双开Bug反馈

### ISSUE THREAD

**Issue by AcademicDog** [society765/yys-auto-yuhun#5]
双开脚本，打手结算函数，133行中有如下描述：
crnd(ts, *pos_jiesuan)    #pos_jiesuan=(1062, 1118, 132, 179)

由于有时候（特别是第一次）打手结算比司机快，此时司机还未发出邀请信号，导致该点击行为重复执行。由于该点正好位于“进度”按钮处，有时候会打开进度表。

**Comment by xwang233** [comment]
感谢你的反馈！结算时需要找到一个矩形范围然后随机反复点击，而且这个范围不能与结算界面，庭院主界面，组队邀请界面冲突。我手边只有个小号，用默认庭院皮肤测试时候还没遇到你说的“进度”按钮。不过我记得去年farm大号时候确实有对电脑版的限制，可能是因为小号等级低还没出现。

![image](https://user-images.githubusercontent.com/24860335/56472601-65297600-642e-11e9-8f6c-1a8fe5c6e21b.png)

![image](https://user-images.githubusercontent.com/24860335/56472502-2ba43b00-642d-11e9-88ef-f00a1a10a043.png)

![image](https://user-images.githubusercontent.com/24860335/56472505-2fd05880-642d-11e9-9364-8db50b1db46e.png)

目前版本中 pos_jiesuan=(1062, 1118, 132, 179) 点击的大概是图中的红色区域，也就是你说的满级后会出现的“进度”按钮。我大概思考了下，可以把结算的点击范围换到图中的绿色区域（头像名牌附近），这样不会与任何 结算/庭院/组队 界面冲突。

唯一可能冲突的地方是，如果左边的聊天栏弹了出来，那么绿色区域会点击到聊天栏，产生不可预料的互动。不知道满级的界面在绿色框这里是否有其他冲突。

绿色区域的坐标是 pos_jiesuan=(189, 333, 23, 76)，如果可以的话，请题主回去测试一下。如果结果没问题，我会尽快把源代码中的坐标也修改了。

**Comment by xwang233** [comment]
已更新 dual.py 的该部分代码，欢迎继续测试。
