### ISSUE TITLE
不知道当我输入了0，之后发现并不能自动开启战斗，是什么问题呢

### ISSUE THREAD

**Issue by xwang233** [society765/yys-auto-yuhun#7]
不知道当我输入了0，之后发现并不能自动开启战斗，是什么问题呢
![image](https://user-images.githubusercontent.com/37180767/56979365-3b99e880-6bac-11e9-981b-4b22f5765143.png)

_Originally posted by @Milo-dd in https://github.com/society765/yys-auto-yuhun/issues/3#issuecomment-488031962_

**Comment by xwang233** [comment]
@Milo-dd 你好，感谢你的反馈！我并没有遇到过这个问题，请提供下你使用的操作系统（win7 还是 win10），哪个脚本文件（Autohotkey, Python, 还是按键精灵，单开还是双开），游戏界面有什么变化（比如点击了哪个按钮，进入了哪个界面，游戏是否进入了战斗，是否有弹窗提示）。

**Comment by Milo-dd** [comment]
win7 64位直接用release的Autohotkey，游戏界面是在御魂挑战界面的，输入0之后未能进入战斗，我尝试终止就弹出加载位图失败的提示。是不是天使插件注册是成功的，但是好像编译时没有注册类。
![image](https://user-images.githubusercontent.com/37180767/57007319-4723f880-6c1a-11e9-84cc-1367e778de20.png)
![image](https://user-images.githubusercontent.com/37180767/57007322-5145f700-6c1a-11e9-8cbb-69b582588c45.png)
![image](https://user-images.githubusercontent.com/37180767/57007333-69b61180-6c1a-11e9-97df-cb29d86eb68a.png)
![image](https://user-images.githubusercontent.com/37180767/57007352-8d795780-6c1a-11e9-9d85-22a3d3c76afd.png)
![image](https://user-images.githubusercontent.com/37180767/57007414-07114580-6c1b-11e9-8f1d-9b66e00e5d80.png)
我是初学者，秉着对游戏的热爱和全自动肝游戏的兴趣想试一下，但好多问题我都还没办法解决

**Comment by Milo-dd** [comment]
![image](https://user-images.githubusercontent.com/37180767/57007469-6d966380-6c1b-11e9-93bd-fa1d172f71cc.png)

**Comment by Milo-dd** [comment]
![image](https://user-images.githubusercontent.com/37180767/57007489-94549a00-6c1b-11e9-9a6c-a2fe4c640e22.png)

**Comment by AcademicDog** [comment]
我觉得你没有管理员方式运行

**Comment by AcademicDog** [comment]
从你的窗口看应该是win7，建议换成那个复古主题试试，可以不用调显示设置

**Comment by Milo-dd** [comment]
其实游戏和ahk都是以管理员权限运行的。
试过还是不行呢。
但我今天发现将dll放在C盘直接注册发现，会注册失败。
![image](https://user-images.githubusercontent.com/37180767/57016965-84ef4400-6c4f-11e9-854f-cf08d2adccb5.png)
![image](https://user-images.githubusercontent.com/37180767/57016973-8de01580-6c4f-11e9-831c-f40d72889e4e.png)
所以我猜想是不是因为我的系统是64位的原因才用不上注册类。
很遗憾没能用上你的辅助，用自己写的早上已经收到了鬼使黑了，要过一段日子才能继续尝试了。
不是很清楚如何去模拟人类玩家，谢谢楼主给的思路我以后会尝试一下。

**Comment by Milo-dd** [comment]
![image](https://user-images.githubusercontent.com/37180767/57017153-6d648b00-6c50-11e9-936b-10ac3d7e8908.png)
![image](https://user-images.githubusercontent.com/37180767/57017162-748b9900-6c50-11e9-8398-722607accbfc.png)

**Comment by AcademicDog** [comment]
64位可以用，我觉得主要原因在于你的win7系统，建议换主题大法试试，用那个复古主题

**Comment by Milo-dd** [comment]
猴，等我先从小黑屋逃出来我再去试试

**Comment by AcademicDog** [comment]
还有需要注意的是，如果你用release的ahk，不需要专门注册dll，但是需要把ahk的exe文件和dll文件放在同一个目录

**Comment by xwang233** [comment]
@Milo-dd 你需要用管理员权限运行AHK脚本和游戏窗口。

我看到弹出了选择点怪的提示窗口，说明插件注册成功，窗口也绑定成功了。如果游戏还是卡在御魂层数界面，没有点击挑战的话，你需要首先确定没有改变游戏窗口大小。然后尝试 __取消__ 勾选  "启用 Aero peek"，"启用透明玻璃"，和"启用桌面组合" 三项，或者像 @AcademicDog 提出的，使用 Win7 的复古主题。

这类游戏脚本需要在鼠标点击的坐标添加随机偏移，不能只点一个固定的位置。另外还可以让鼠标点击的间隔变成一段随机范围，而不是一个固定的时间间隔。理论上讲，做到这些应该就没问题了，但是如果你同时开太多号，或者挂机太长时间，可能会触发网易的检测机制。这一点我也不是很确定。

**Comment by Milo-dd** [comment]
我发现了问题所在
![image](https://user-images.githubusercontent.com/37180767/57129845-3a460700-6dca-11e9-9838-3bc8f516f2f2.png)
![image](https://user-images.githubusercontent.com/37180767/57129860-4a5de680-6dca-11e9-9642-a98f0d513e31.png)
当脚本文件与yys的neox.xml
中的文件长宽不匹配时就会出现问题，同时需要把自动调整大小改成false就可以了。

**Comment by Milo-dd** [comment]
应该是之前我替换过neox文件，导致问题出现，现在已经修改好了估计就没有问题了

**Comment by xwang233** [comment]
@Milo-dd 是的。点怪，点按钮的位置都是固定坐标相对于原始的窗口尺寸。因为TS插件 SetClientSize 会使得窗口边框变得奇怪，所以我把强制变换窗口尺寸的语句注释掉了，并且要求用户使用默认窗口尺寸。当然你也可以取消掉那两行的注释，使用TS插件来改变游戏窗口尺寸，效果是一样的。

**Comment by Milo-dd** [comment]
今天用两个号测试了自动点怪，会有被鬼使黑的风险。好像是，当你体力没有用完的时候他会故意弹出一个窗口，说你体力用完了。结果脚本没有停止回来看已经收到鬼使黑来信了

**Comment by Milo-dd** [comment]
不自动点怪还是不会有问题的
