### ISSUE TITLE
您好！请问有计划推出组队模式吗？

### ISSUE THREAD

**Issue by Williamongh** [society765/yys-auto-yuhun#9]
感谢作者，解放了我的双手，但是请问作者有计划推出组队模式吗（自动检测接受组队按钮，自动检测奖励页面）？

**Comment by xwang233** [comment]
感谢你的反馈！关于你说的自动接受组队模式，是单人作为司机/打手，然后与其他玩家合作的脚本么？因为这种脚本需要与其他玩家合作，存在的变数太大（比如：另一名玩家掉线，或者邀请太慢等），而导致脚本逻辑不好写，所以我没有类似的计划。如果你确实有需求的话，可以参考我的双开脚本里，把不需要的司机/打手部分注释掉，应该可以近似满足你的需求。
